DROP TABLE IF EXISTS Forum_user CASCADE;
DROP TABLE IF EXISTS User_group CASCADE;
DROP TABLE IF EXISTS Post CASCADE;
DROP TABLE IF EXISTS Topic_group CASCADE;
DROP TABLE IF EXISTS Membership CASCADE;
DROP TABLE IF EXISTS Thread CASCADE;